package com.smartgym.manager.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StravaAccountAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStravaAccountAllPropertiesEquals(StravaAccount expected, StravaAccount actual) {
        assertStravaAccountAutoGeneratedPropertiesEquals(expected, actual);
        assertStravaAccountAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStravaAccountAllUpdatablePropertiesEquals(StravaAccount expected, StravaAccount actual) {
        assertStravaAccountUpdatableFieldsEquals(expected, actual);
        assertStravaAccountUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStravaAccountAutoGeneratedPropertiesEquals(StravaAccount expected, StravaAccount actual) {
        assertThat(actual)
            .as("Verify StravaAccount auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStravaAccountUpdatableFieldsEquals(StravaAccount expected, StravaAccount actual) {
        assertThat(actual)
            .as("Verify StravaAccount relevant properties")
            .satisfies(a -> assertThat(a.getStravaUserId()).as("check stravaUserId").isEqualTo(expected.getStravaUserId()))
            .satisfies(a -> assertThat(a.getAccessToken()).as("check accessToken").isEqualTo(expected.getAccessToken()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStravaAccountUpdatableRelationshipsEquals(StravaAccount expected, StravaAccount actual) {
        // empty method
    }
}
